development:
  adapter: postgresql
  database: muro_development
  pool: 5
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  database: muro_test
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: muro_production
  pool: 5
  timeout: 5000
  username:
  password:
